<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map([
    '__library_version__' => 2,
  'class' => [
    'ForuConfiguration' => 'src/ForuConfiguration.php',
    'ForuDiffWorkflow' => 'src/ForuDiffWorkflow.php',
    'ForuLandWorkflow' => 'src/ForuLandWorkflow.php',
],
  'function' => [],
  'xmap' => [
    'ForuConfiguration' => 'ArcanistConfiguration',
    'ForuDiffWorkflow' => 'ArcanistWorkflow',
    'ForuLandWorkflow' => 'ArcanistWorkflow',
],
]);
